package com.epam.travelAgency.controller.command;

public enum CommandName {
    GOTOLOGINPAGE, AUTHORISATION, REGISTRATION, GOTOMAINPAGE, SHOWWRONGMODAL,
    SHOWCATEGORIES, GOTOUSERPAGE, GOTOREGISTRATIONPAGE, LOGOUT, GOTOCHILLPAGE,
    SHOWCHILLTOURSDATA, GOTOEXCURSIONPAGE, SHOWEXCURSIONDATA, GOTOSHOPPINGPAGE,
    SHOWSHOPPINGDATA
}
